### ISSUE TITLE
CYOA

### ISSUE THREAD

**Issue by willhobson85** [Ant-Shell/rancid-tomatillos#11]
**Please Describe The Problem To Be Solved**

1) The Movie Database (TMDB) API for fetching movie data:
https://developers.themoviedb.org/3/getting-started/introduction

2) Add a search/filtering functionality for movies 

3) Express Server Buildout:
For user login and adding ratings (and perhaps favoriting / which movies have been watched)

4) Can also do a deploy for a quick win as well - would satisfy the CYOA requirement if time becomes a factor

**Comment by Ant-Shell** [comment]
The Movie Database (TMDB) API for fetching movie data has been completed!

**Comment by Ant-Shell** [comment]
Closing, but will be doing these as well:

Add a search/filtering functionality for movies (attempt)
Deploy (for sure!)
