### ISSUE TITLE
Wishlist Loading Screen

### ISSUE THREAD

**Issue by willhobson85** [Ant-Shell/rancid-tomatillos#17]
**Please Describe The Problem To Be Solved**
Loading Screen

**(Optional): Suggest A Solution**
Render loading screen if there is no length to the all movies array in state

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by Ant-Shell** [comment]
Maybe set state in App something like this.setstate.errorMessage

Then pass the result of that down to error/loading screen components and render based on state from App

**Comment by willhobson85** [comment]
Completed!
