### ISSUE TITLE
Wishlist - Install Glide.js for card carousel

### ISSUE THREAD

**Issue by Ant-Shell** [Ant-Shell/rancid-tomatillos#22]
**Please Describe The Problem To Be Solved**
Use glide.js for move card carousel

**(Optional): Suggest A Solution**

For comparison - from Dinne:

const config = {
  type: "carousel",
  startAt: 0,
  perView: 1,
};
new Glide(".glide", config).mount();

**Comment by willhobson85** [comment]
Completed with Swiper
